steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/adori-v2', '.']
    env:
      - 'NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_c2VjdXJlLWR1Y2tsaW5nLTYxLmNsZXJrLmFjY291bnRzLmRldiQ'
      - 'NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in'
      - 'NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up'
      - 'NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL=/dashboard'
      - 'NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL=/dashboard'

images:
  - 'gcr.io/$PROJECT_ID/adori-v2'
