steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '--build-arg=NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${_NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}'
      - '--build-arg=CLERK_SECRET_KEY=${_CLERK_SECRET_KEY}'
      - '--build-arg=NEXT_PUBLIC_CLERK_SIGN_IN_URL=${_NEXT_PUBLIC_CLERK_SIGN_IN_URL}'
      - '--build-arg=NEXT_PUBLIC_CLERK_SIGN_UP_URL=${_NEXT_PUBLIC_CLERK_SIGN_UP_URL}'
      - '--build-arg=NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL=${_NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL}'
      - '--build-arg=NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL=${_NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL}'
      - '-t'
      - 'gcr.io/applied-honor-105708/adori-tes'
      - '.'

images:
  - 'gcr.io/applied-honor-105708/adori-test'
